@extends('pdf.layout')

@section('title', 'Payment Instructions')
@section('document-type', 'PAYMENT INSTRUCTIONS')

@section('content')
<h1>Payment Instructions</h1>

<div class="info-box highlight">
    <strong>Transaction Reference:</strong> <span class="reference">{{ $reference }}</span><br>
    <strong>Payment Due:</strong> {{ $dueDate ? $dueDate->format('d.m.Y H:i') : 'Within 48 hours' }}
</div>

<h2>Amount to Transfer</h2>
<div class="info-box success text-center">
    <p class="amount" style="font-size: 24pt;">€{{ number_format($amount, 2, ',', '.') }}</p>
</div>

<h2>Bank Transfer Details</h2>
<table>
    <tr>
        <th colspan="2">Recipient Bank Information</th>
    </tr>
    <tr>
        <td><strong>Account Holder:</strong></td>
        <td>{{ $bankDetails['account_holder'] }}</td>
    </tr>
    <tr>
        <td><strong>Bank Name:</strong></td>
        <td>{{ $bankDetails['bank_name'] }}</td>
    </tr>
    <tr>
        <td><strong>IBAN:</strong></td>
        <td style="font-family: monospace; letter-spacing: 2px;">{{ $bankDetails['iban'] }}</td>
    </tr>
    @if($bankDetails['bic'])
    <tr>
        <td><strong>BIC/SWIFT:</strong></td>
        <td style="font-family: monospace;">{{ $bankDetails['bic'] }}</td>
    </tr>
    @endif
</table>

<div class="info-box" style="background-color: #fff3cd; border-left: 4px solid #ffc107;">
    <strong>⚠️ Important: Payment Reference</strong><br><br>
    Please include the following reference in your bank transfer:<br>
    <strong style="font-size: 14pt; font-family: monospace;">{{ $reference }}</strong><br><br>
    <small>This reference is required to match your payment to this transaction.</small>
</div>

<h2>Payment Instructions</h2>
<ol>
    <li><strong>Initiate the bank transfer</strong> using the details provided above.</li>
    <li><strong>Include the reference number</strong> <code>{{ $reference }}</code> in the payment description.</li>
    <li><strong>Transfer the exact amount</strong> of €{{ number_format($amount, 2, ',', '.') }}.</li>
    <li><strong>Upload proof of payment</strong> in your SafeTrade dashboard after completing the transfer.</li>
    <li><strong>Wait for verification</strong> - AutoScout24 will verify your payment within 1-2 business days.</li>
</ol>

<h2>After Payment</h2>
<p>Once your payment is verified:</p>
<ul>
    <li>You will receive a confirmation email.</li>
    <li>You can schedule the vehicle pickup with the seller.</li>
    <li>The seller will be notified that the funds are secured.</li>
</ul>

<div class="info-box">
    <strong>Need Help?</strong><br>
    If you have any questions about the payment process, please contact our SafeTrade support team:
    <ul>
        <li>Email: safetrade@autoscout24.com</li>
        <li>Phone: +49 89 123 456 789</li>
    </ul>
</div>

<p class="small mt-20 text-center">
    This document contains sensitive banking information. Please keep it secure.<br>
    Generated by AutoScout24 SafeTrade on {{ now()->format('d.m.Y H:i') }}
</p>
@endsection
